TEST-1

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -130,18 +130,31 @@ jobs:
               --query "TargetHealthDescriptions[0].TargetHealth.State" \
               --output text)
 
-            echo "Attempt $i - Status: $STATUS"
+            echo "waiting for targets to become healthy ..."
 
-            if [ $"STATUS" == "healthy" ]; then
-              echo "Target is healthy"
-              exit 0
-            fi
+            ATTEMPTS=30
+            COUNT=1
 
-            sleep 10
-          done
+            while [ $COUNT -le $ATTEMPTS ]; do
+              STATES=$(aws elbv2 describe-target-health \
+                --target-group-arn $TG_ARN \
+                --query "TargetHealthDescriptions[].TargetHealth.State" \
+                --output text)
+              echo "attempt $COUNT- States: $STATES"
 
-          echo "deployment unhelathy after waiting"
-          exit 1
+              if [[ "$STATES" == *"healthy"* ]]; then
+                echo "Targets are healthy!"
+                exit 0
+              fi
+
+              if [[ "$STATES" == *"unhealthy"* ]]; then
+                echo "Targets are unhealthy. Failing deployment."
+                exit 1
+              fi
+
+              sleep 10
+              COUNT=$((COUNT + 1))
+            done
   
       - name: Switch traffic
         if: success()
